<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'V2luOOS5i+Wutg==');
$cfg_Cs[2]=array(0,1,1,'6LWE6K6v');
$cfg_Cs[5]=array(0,1,1,'6Iu55p6c5LmL5a62');
$cfg_Cs[6]=array(0,1,1,'6LC35q2M5LmL5a62');
$cfg_Cs[7]=array(0,1,1,'5aOB57q45LmL5a62');
$cfg_Cs[10]=array(1,1,1,'V2luOOW/q+iurw==');
$cfg_Cs[11]=array(1,1,1,'V2luOOWtpumZog==');
$cfg_Cs[12]=array(1,1,1,'V2luOOezu+e7n+S4i+i9vQ==');
$cfg_Cs[13]=array(1,1,1,'V2luOOi9r+S7tuS4i+i9vQ==');
$cfg_Cs[14]=array(1,1,1,'V2luOOS4u+mimA==');
$cfg_Cs[15]=array(2,1,1,'SVTotYTorq8=');
$cfg_Cs[16]=array(2,1,1,'UVHkuYvlrrY=');
$cfg_Cs[17]=array(2,1,1,'SVTkuYvlpJY=');
?>