<?php
$z[0]=Array("field","",68,96);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",114,143);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",182,210);
$z[2][4]=array();
$z[2][4]['name']="typeurl";
$z[3]=Array("arclist","\r\n\r\n   <li class=\"\r\n[field:pubdate runphp='yes']  \r\n\$a=\"new\"; \r\n\$b=\"\";    \r\n\$c=strftime(\"%d\",\"@me\");\r\n\$d=date(d); \r\nif(\$c==\$d) @me = \$a;  \r\nelse @me = \$b;  \r\n[/field:pubdate]   \r\n   \"><span class=\"date\">[field:pubdate runphp='yes']  \r\n\$a=\"日\"; \r\n\$b=\"今日\";    \r\n\$c=strftime(\"%Y%m%d\",\"@me\");\r\n\$d=date(Ymd); \r\n\$e=strftime(\"%d\",\"@me\");\r\nif(\$c==\$d) @me = \$b;  \r\nelse @me = \$e.\$a;  \r\n[/field:pubdate]</span><span class=\"title\"><a target=\"_blank\" href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\">[field:title/]</a></span></li>\r\n \r\n    ",273,856);
$z[3][4]=array();
$z[3][4]['row']="12";
$z[3][4]['titlelen']="60";

?>