<?php
$z[0]=Array("field","",67,95);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",113,142);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",181,209);
$z[2][4]=array();
$z[2][4]['name']="typeurl";
$z[3]=Array("arclist","\n\n   <li class=\"\n[field:pubdate runphp='yes']  \n\$a=\"new\"; \n\$b=\"\";    \n\$c=strftime(\"%d\",\"@me\");\n\$d=date(d); \nif(\$c==\$d) @me = \$a;  \nelse @me = \$b;  \n[/field:pubdate]   \n   \"><span class=\"date\">[field:pubdate runphp='yes']  \n\$a=\"日\"; \n\$b=\"今日\";    \n\$c=strftime(\"%Y%m%d\",\"@me\");\n\$d=date(Ymd); \n\$e=strftime(\"%d\",\"@me\");\nif(\$c==\$d) @me = \$b;  \nelse @me = \$e.\$a;  \n[/field:pubdate]</span><span class=\"title\"><a target=\"_blank\" href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\">[field:title/]</a></span></li>\n \n    ",270,832);
$z[3][4]=array();
$z[3][4]['row']="12";
$z[3][4]['titlelen']="60";

?>