<?php
$z[0]=Array("pubdate","  \r\n\$a=\"new\"; \r\n\$b=\"\";    \r\n\$c=strftime(\"%d\",\"@me\");\r\n\$d=date(d); \r\nif(\$c==\$d) @me = \$a;  \r\nelse @me = \$b;  \r\n",13,167);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("pubdate","  \r\n\$a=\"日\"; \r\n\$b=\"今日\";    \r\n\$c=strftime(\"%Y%m%d\",\"@me\");\r\n\$d=date(Ymd); \r\n\$e=strftime(\"%d\",\"@me\");\r\nif(\$c==\$d) @me = \$b;  \r\nelse @me = \$e.\$a;  \r\n",196,391);
$z[1][4]=array();
$z[1][4]['runphp']="yes";
$z[2]=Array("arcurl","",443,458);
$z[2][4]=array();
$z[3]=Array("fulltitle","",467,485);
$z[3][4]=array();
$z[4]=Array("title","",487,501);
$z[4][4]=array();

?>