<?php
$z[0]=Array("pubdate","  \n\$a=\"new\"; \n\$b=\"\";    \n\$c=strftime(\"%d\",\"@me\");\n\$d=date(d); \nif(\$c==\$d) @me = \$a;  \nelse @me = \$b;  \n",12,159);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("pubdate","  \n\$a=\"日\"; \n\$b=\"今日\";    \n\$c=strftime(\"%Y%m%d\",\"@me\");\n\$d=date(Ymd); \n\$e=strftime(\"%d\",\"@me\");\nif(\$c==\$d) @me = \$b;  \nelse @me = \$e.\$a;  \n",189,376);
$z[1][4]=array();
$z[1][4]['runphp']="yes";
$z[2]=Array("arcurl","",435,450);
$z[2][4]=array();
$z[3]=Array("fulltitle","",459,477);
$z[3][4]=array();
$z[4]=Array("title","",479,493);
$z[4][4]=array();

?>