<?php  exit();
/*
Page: /dede/index_menu_load.php?openitem=7
Error: Table 'c0001_blue.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2017-06-19 22:42:20
*/
?>
<?php  exit();
/*
Page: /dede/sys_data.php
Error: Table 'c0001_blue.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT addtable FROM `dede_channeltype` </font>
Time2017-06-19 22:54:09
*/
?>
